### PR TITLE
IAP firewall checks

### PR DESCRIPTION
**Pull request by saisirishreddy**
1. IAP firewall checks with possible combinations of ports and sources

2. Modified query for _2.2 Ensure That Sinks Are Configured for All Log Entries_

### Checklist
- [ ] Issue(s) linked

### CODE REVIEW

**Comment by misraved** [comment]
Great work @saisirishreddy 👍 !!

Could you please share some insights on why you made this change, was the previous query not working out correctly? 

Please feel free to attach any docs that you used as a reference for making the changes 👍.

**Comment by saisirishreddy** [comment]
_CIS_v200_3_10 Use Identity Aware Proxy (IAP) to Ensure Only Traffic From Google IP Addresses are 'Allowed'_  do not predefine ports or port ranges.
- It is up to the organizations to define , if the traffic is allowed on specified ports from the Google source IP ranges
- I only populated most commonly used ports with IAP 22, 3389, 80, 443

the current query for _CIS_v200_3_10_  is _compute_firewall_allow_tcp_connections_proxied_by_iap_ which covers a subset of the baseline.

Firewall rules can be defined with multiple ports and multiple source IP ranges. The current query checks for the source IP ranges to contain all three Google IP's. There is a possibility that the firewall rules are split with Source IP ranges or Ports or both. 

In my view this seemed most optimal, although there might me firewall rules defined with other ports and combinations of Source IPs

**Comment by misraved** [comment]
@saisirishreddy thanks for the explanation. The update seems reasonable 👍.

Could you please attach the output query results and snapshots of the corresponding GCP firewall rules with sensitive information removed?

**Comment by saisirishreddy** [comment]
I would also recommend to add a check for Firewall status (disabled) for this and other firewall queries. 

image

**Comment by saisirishreddy** [comment]
I added a query change for query _2.2 Ensure That Sinks Are Configured for All Log Entries_  

Instead of checking for an log sink with empty inclusion filter, check if the default log sink created by Google is altered.

Google by default logs all enabled logs in two Cloud Logging buckets that are created by Google, only one of the log sink and bucket configuration can be changed/deleted.

**Review by madhushreeray30 — DISMISSED** [review]

**Comment by madhushreeray30** [comment]
@saisirishreddy Regarding the changes made in the PR a couple of things to be noted:
 - The change made in the `compute_firewall_allow_connections_proxied_by_iap` query is not needed because this query is being used in `cis_v120_3_10` which mentions the inclusion of only source IPs `130.211.0.0/22` and `35.191.0.0/16`. However as per `cis_v200_3_10` the allowed source IPs are `35.235.240.0/20`, `130.211.0.0/22` and `35.191.0.0/16` so we can make the suggested change in the `compute_firewall_allow_tcp_connections_proxied_by_iap` query. Could you please make the changes to the `compute_firewall_allow_tcp_connections_proxied_by_iap` query instead.
 - The change made for the `logging_sink_configured_for_all_resource` query is not needed because the CIS document clearly states that the filter needs to be kept empty for at least one sink. Our query is strictly following the CIS document.
 
image

**Comment by madhushreeray30** [comment]
@saisirishreddy We are closing this PR as the changes are not needed. We will raise another PR addressing the changes in `compute_firewall_allow_tcp_connections_proxied_by_iap` query for `cis_v200_3_10`.

**Pull request closed without merging**
